Copyright (C) "BY ULLA"
IT
PUOI UTILIZZARE QUESTA MOD IN MINETEST,
PUOI INTEGRARLA IN ALTRE MOD PER MINETEST 
O UTILIZZARNE  SINGOLE PARTI
QUESTA MOD HA SOLO UNA RESTRIZIONE : 
OGNI PARTE ORIGINALE CREATA DA ME (TEXTURES MODELLI ETC..) 
NON PUÒ ESSERE UTILIZZATA PER SCOPI PUBBLICITARI O ALTRI GIOCHI ESCLUDENDO  LA MIA APPROVAZIONE IN OGNI CASO VA INDICATO IL MIO NOME >ANDREA DI PIETRO ULLA < 
PER QUANTO RIGUARDA IL CODICE SCRITTO,  LE LICENZE SONO QUELLE DI MINETEST DEFAULT 
ANCHE PER IL CODICE AGGIUNTO  O MODIFICATO ,
IL CODICE DELLE ARMATURE DIPENDONO DALLA LICENZA DI 3D_ARMOR 
3D Armor - Visible Player Armor
===============================

License Source Code: Copyright (C) 2013-2018 Stuart Jones - LGPL v2.1

Armor Textures: Copyright (C) 2017-2018 davidthecreator - CC-BY-SA 3.0

Special credit to Jordach and MirceaKitsune for providing the default 3d character model.

QUESTA LICENZA DEVE ESSERE INSERITA IN OGNI PROGETTO CHE USA LA MOD O PARTE DI ESSA .
QUESTA MOD PUÒ ESSERE MIGLIORATA , SENZA  ESCLUDERE IL MIO NOME  PER AVERE IDEATO E CREATO LA MOD   
PUOI UTILIZZARLA NEI TUOI VIDEO PER MINETEST
EN
YOU CAN USE THIS MOD IN MINETEST,
YOU CAN INTEGRATE IT IN OTHER MOD FOR MINETEST
OR USE SINGLE PARTS
THIS MOD HAS A RESTRICTION ONLY:
EVERY ORIGINAL PART MADE BY ME (TEXTURES MODELS ETC ..)
IT CAN NOT BE USED FOR ADVERTISING PURPOSES OR OTHER GAMES BY EXCLUDING MY APPROVAL IN ANY CASE IT SHOWS MY NAME> ANDREA DI PIETRO ULLA <
WITH REGARD TO THE WRITTEN CODE, THE LICENSES ARE THOSE OF MINETEST DEFAULT
ALSO FOR THE ADDED OR MODIFIED CODE,
THE ARMORIES CODE DEPENDS ON THE 3D_HARMOR LICENSE :
(3D Armor - Visible Player Armor
===============================

License Source Code: Copyright (C) 2013-2018 Stuart Jones - LGPL v2.1

Armor Textures: Copyright (C) 2017-2018 davidthecreator - CC-BY-SA 3.0

Special credit to Jordach and MirceaKitsune for providing the default 3d character model.)
THIS LICENSE MUST BE INSERTED IN ANY PROJECT WHICH USES MOD OR PART OF IT.
THIS MOD CAN BE IMPROVED, WITHOUT EXCLUDING MY NAME TO HAVE IDEATED AND CREATED MOD
YOU CAN USE IT IN YOUR VIDEOS FOR MINETEST
